
#lista de los productos (no se actualiza automaticamente)
get http://localhost:8080/

#lista en tiempo real de los productos manejada con socketServer
get http://localhost:8080/realTimeProducts

#url para crear un nuevo carrito
post http://localhost:8080/

#url que agrega un producto a un carrito previamente creado
post http://localhost:8080/cart/64405caade687032ad849594/products/643efe611602f47420e2c4d7

#link para aceder al chat con socketServer
post http://localhost:8080/chat

#retorna los productos en la base de datos
get  http://localhost:8080/products/

#retorna un producto con un id detenrminado
get  http://localhost:8080/products/643efe611602f47420e2c4d5

#elimina de forma logica un producto, poniendo su status en false
delete  http://localhost:8080/products/643efe611602f47420e2c4d5

#carga un nuevo producto en la base de datos
post  http://localhost:8080/products/
content-type: application/json
{
    "title": "Titulo de ejemplo",
    "description":"Descriocion de ejemplo",
    "price":10,
    "thumbnails": "sin url",
    "code":"productEjemplo",
    "stock":10,
    "status":true,
    "category":"categoria ejemplo"
}


